---
- name: Determine architecture for LazyDocker
  ansible.builtin.set_fact:
    lazydocker_arch: "{{ 'x86_64' if ansible_facts['architecture'] == 'x86_64' else 'arm64' }}"
  when: ansible_facts['architecture'] in ['x86_64', 'aarch64', 'arm64']

- name: Download LazyDocker binary archive
  ansible.builtin.get_url:
    url: "https://github.com/jesseduffield/lazydocker/releases/download/v{{ lazydocker_version }}/lazydocker_{{ lazydocker_version }}_Linux_{{ lazydocker_arch }}.tar.gz"
    dest: /tmp/lazydocker.tar.gz
    mode: "0644"

- name: Extract LazyDocker tarball
  ansible.builtin.unarchive:
    src: /tmp/lazydocker.tar.gz
    dest: /tmp
    remote_src: true

- name: Move lazydocker binary to destination
  ansible.builtin.copy:
    src: /tmp/lazydocker
    dest: "{{ lazydocker_bin_dir }}/lazydocker"
    mode: "0755"
    remote_src: true

- name: Clean up LazyDocker temp files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/lazydocker
    - /tmp/lazydocker.tar.gz
