---
# ==============================================================================
# Handlers for ttyd role
# ==============================================================================

- name: restart ttyd
  ansible.builtin.systemd:
    name: ttyd
    state: restarted
    daemon_reload: true

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
