---
- name: Install special kali security packages
  ansible.builtin.package:
    name: "{{ kali_packages }}"
    state: present

- name: Ensure tmux resurrect directory exists
  ansible.builtin.file:
    path: "{{ kali_user_home }}/.local/share/tmux/resurrect"
    state: directory
    owner: "{{ kali_user }}"
    group: "{{ kali_user }}"
    mode: "0755"

- name: Install tmux resurrect last file
  ansible.builtin.copy:
    dest: "{{ kali_user_home }}/.local/share/tmux/resurrect/last"
    owner: "{{ kali_user }}"
    group: "{{ kali_user }}"
    mode: "0644"
    content: |
      pane	action	1	1	:*	1	{{ ansible_facts['hostname'] }}	:{{ kali_user_home }}	1	zsh	:
      pane	action	2	0	:-	1	{{ ansible_facts['hostname'] }}	:{{ kali_user_home }}	1	zsh :
      pane	action	3	0	:-	1	{{ ansible_facts['hostname'] }}	:{{ kali_user_home }}	1	zsh	:
      pane	general	1	0	:-	1	{{ ansible_facts['hostname'] }}	:{{ kali_user_home }}	1	zsh	:
      pane	general	2	1	:*	1	{{ ansible_facts['hostname'] }}	:{{ kali_user_home }}	1	zsh	:
      pane	general	3	0	:-	1	{{ ansible_facts['hostname'] }}	:{{ kali_user_home }}	1	zsh	:
      pane	scan	1	1	:*	1	{{ ansible_facts['hostname'] }}	:{{ kali_user_home }}	1	zsh	:
      pane	scan	2	0	:-	1	{{ ansible_facts['hostname'] }}	:{{ kali_user_home }}	1	zsh	:
      pane	ssh	1	1	:*	1	{{ ansible_facts['hostname'] }}	:{{ kali_user_home }}	1	zsh	:
      pane	ssh	2	0	:-	1	{{ ansible_facts['hostname'] }}	:{{ kali_user_home }}	1	zsh	:
      window	action	1	:general	1	:*	b25e,80x24,0,0,1	off
      window	action	2	:msf	0	:-	b267,80x24,0,0,10	off
      window	action	3	:extra	0	:-	b268,80x24,0,0,11	off
      window	general	1	:general	0	:-	b25f,80x24,0,0,2	off
      window	general	2	:extra	1	:*	b260,80x24,0,0,3	off
      window	general	3	:vpn	0	:-	b261,80x24,0,0,4	off
      window	scan	1	:nmap	1	:*	b263,80x24,0,0,6	off
      window	scan	2	:extra	0	:-	b264,80x24,0,0,7	off
      window	ssh	1	:netcat	0	:-	b265,80x24,0,0,8	off
      window	ssh	2	:extra	1	:*	b266,80x24,0,0,9	off
      state	action	general

- name: Append nmap configuration to /etc/grc.conf
  ansible.builtin.blockinfile:
    path: /etc/grc.conf
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK - NMAP GRC"
    block: |
      \b\w+\b.*nmap\b
      conf.nmap

      \b\w+\b*nmap.txt\b
      conf.nmap
