---
- name: Setup development environment
  hosts: all
  become: true

  pre_tasks:
    - name: install updates
      import_tasks: ../tasks/update.yaml

  tasks:
    - name: Install base packages
      package:
        name:
          - gcc
          - python3
          - git
          - btop
          - curl
          - wget
          - unzip
          - tar
          - tmux
        state: present

    - name: zsh setup
      import_tasks: ../tasks/zsh.yaml

    - name: Clone tmux plugin manager (TPM)
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: "/home/{{ ansible_user }}/.tmux/plugins/tpm"
        version: master
      become_user: "{{ ansible_user }}"

    - name: fzf setup
      import_tasks: ../tasks/fzf.yaml
    
    - name: neovim setup
      import_tasks: ../tasks/nvim.yaml

    - name: lazygit setup
      import_tasks: ../tasks/lazygit.yaml

    - name: dotfiles setup
      import_tasks: ../tasks/dotfiles.yaml
      vars:
        dotfiles_repo: "https://gitlab.com/rootminusone8004/Dotfiles"
        dotfiles_branch: "server"
