---
- name: Setup development environment
  hosts: all
  become: true
  roles:
    - role: common
      tags: [common, minimal]
    - role: zsh
      tags: [zsh]
    - role: tmux
      tags: [tmux, minimal]
    - role: fzf
      tags: [fzf, minimal]
    - role: neovim
      tags: [neovim]
    - role: lazygit
      tags: [lazygit]
    - role: dotfiles
      tags: [dotfiles, minimal]
