- name: Setup development environment
  hosts: all
  become: true

  pre_tasks:
    - name: install updates
      tags: minimal
      import_tasks: ../tasks/update.yaml

  tasks:
    - name: Install special kali packages
      package:
        name:
          - openvpn
          - nmap
          - grc
          - gobuster
          - wordlists
          - seclists
          - metasploit-framework
          - sqlmap
        state: present

    - name: Append nmap configuration to /etc/grc.conf
      ansible.builtin.blockinfile:
        path: /etc/grc.conf
        insertafter: EOF
        marker: ""
        block: |
          # nmap file
          \b\w+\b.*nmap\b
          conf.nmap
    
          \b\w+\b*nmap.txt\b
          conf.nmap
