- name: Setup development environment
  hosts: all
  become: true

  pre_tasks:
    - name: install updates
      tags: minimal
      import_tasks: ../tasks/update.yaml

  tasks:
    - name: Install special kali packages
      package:
        name:
          - openvpn
          - nmap
          - gobuster
          - wordlists
          - seclists
          - metasploit-framework
          - sqlmap
        state: present
