---
- name: Setup Kubernetes Nodes (Controller + Workers)
  hosts: all
  become: true
  roles:
    - role: docker
      vars:
        docker_install_engine: false
      tags: [docker, containerd]
    - role: kubeadm
      vars:
        kubeadm_role: node
      tags: [kubeadm, node]

- name: Initialize Kubernetes on Controller Node Only
  hosts: control_plane
  become: true
  roles:
    - role: kubeadm
      vars:
        kubeadm_role: control_plane
      tags: [kubeadm, control_plane]