---
- name: Install Minikube on Linux
  hosts: all
  become: true
  roles:
    - role: docker
      tags: [docker]
    - role: kubectl
      tags: [kubectl]
    - role: minikube
      tags: [minikube]
